# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Linting, formatting, and tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      PY_VERSION: 3.8

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ env.PY_VERSION }}

    - name: Install pip (and get cache dir)
      id: cache_pip
      run: |
        python -m pip install --upgrade pip
        echo "::set-output name=dir::$(pip cache dir)"

    - name: Cache pip
      uses: actions/cache@v2
      with:
        path: ${{ steps.cache_pip.outputs.dir }}
        key: ${{ runner.os }}-pip-${{ env.PY_VERSION }}-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-${{ env.PY_VERSION }}
          ${{ runner.os }}-pip-

    - name: Install dependencies
      run: |
        pip install pylint pytest black
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Check formatting (black)
      run: black --diff --check .

    - name: Install dist_ir
      run: python setup.py install

    - name: Test with pytest
      run: python -m pytest
